Configurable Database Connection
codestudiollc/laravel-totem pull request #130
Opened 2018-12-13 15:29 UTC by qschmick

Changes based on request from #73 

- Setup full package to be able to be run using a different database connection
- Extended migration abstract class
- Updated TotemModel underlying connection so all models are updated from single location

2018-12-14 03:20 UTC, roshangautam requested changes
Thanks for working on this. Please look at the comments I've left.

2018-12-14 03:20 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> +            if (Schema::connection((new TotemModel)->getConnectionName() ?? Schema::getConnection()->getName())
Please define constants like TOTEM_PATH for table prefix and database connection both. For that you will have to move `mergeConfigFrom` to the top of this method. And then something like this:

```       
if (! defined('TOTEM_TABLE_PREFIX')) {
    define('TOTEM_TABLE_PREFIX', config('totem.table_prefix'));
}

if (! defined('TOTEM_DB_CONNECTION')) {
    define('TOTEM_DB_CONNECTION', config('totem.database_connection', env('DB_CONNECTION')));
}
```

Once you have the constants defined you can use them as follows

```
if (Schema::connection(TOTEM_DB_CONNECTION)->hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
    $this->app->register(ConsoleServiceProvider::class);
}
```

After this refactor you can get rid of `getConnection` method in TotemModel

2018-12-14 03:20 UTC, roshangautam commented on src/Database/TotemMigration.php
> +    public function getConnection()
instead of adding a new a grabbing the connection name from `Schema` facade you can do something like this:

```
    public function __construct()
    {
        if (! defined('TOTEM_DB_CONNECTION')) {
            define('TOTEM_DB_CONNECTION', config('totem.database_connection', env('DB_CONNECTION')));
        }
    }
```

and get rid of this function. Finally update all the migrations to use this constant instead of calling the `getConnection` function

2018-12-14 04:14 UTC, qschmick commented on src/Database/TotemMigration.php
> +    public function getConnection()
@roshangautam This is overriding the built in `getConnection` method from the underlying `Illuminate\Database\Migrations\Migration` class. This is to ensure the connection is persisted into the model on static function calls and instantiation without overriding the default connection for the rest of the app.
Also, we cannot be sure that `env('DB_CONNECTION')` will be the correct fail back so we should instead use the connection currently held by the Schema facade.

2018-12-14 04:33 UTC, roshangautam reviewed
Looks much better. Thanks for the iteration. Did you test the changes for both cases, one with separate connection and one without?

2018-12-14 04:38 UTC, qschmick commented
@roshangautam Yes, tested migrations with and without custom DB connection. Migrations ran, added task, and ran to see results populate.

2018-12-14 04:39 UTC, roshangautam approved these changes

2018-12-14 04:40 UTC, merged

2019-01-17 13:00 UTC, vesper8 commented on src/Database/TotemMigration.php
> +    public function getConnection()
And also Laravel's guide makes it clear that you should never ever under any circumstance be accessing env() outside of the /config/ folder