Added cache usage so we stop checking for the table after it exists
codestudiollc/laravel-totem pull request #131
Opened 2018-12-13 15:52 UTC by qschmick

Minor enhancement so we stop checking for the table after it is found.

Requested in issue #127

2018-12-14 02:06 UTC, roshangautam commented
can you please fix the failing tests?

2018-12-14 02:14 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> +            $exists = Cache::get('totem.table.'.config('totem.table_prefix').'tasks', false);
you can possibly rewrite this as following:
`$exists = Cache::get('totem.table.'.config('totem.table_prefix').'tasks', Schema::hasTable(config('totem.table_prefix').'tasks')`

This will save you multiple if statements. Also, as we are using config('totem.table_prefix').'tasks' repeatedly, why not save it in a variable and then use that variable instead.

2018-12-14 02:14 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> +            $exists = Cache::get('totem.table.'.config('totem.table_prefix').'tasks', false);
Also let's refactor this logic out to a separate function

2018-12-14 02:14 UTC, roshangautam requested changes
left you a few comments

2018-12-14 04:24 UTC, qschmick commented on src/Providers/TotemServiceProvider.php
> +            $exists = Cache::get('totem.table.'.config('totem.table_prefix').'tasks', false);
@roshangautam We moved the prefix into a const in [PR 130](https://github.com/codestudiohq/laravel-totem/pull/130) and also refactored it into a static method. Once that is approved and merged in I'll update this branch

2018-12-14 04:34 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> +            $exists = Cache::get('totem.table.'.config('totem.table_prefix').'tasks', false);
Thanks @qschmick . Appreciate it.

2018-12-14 05:09 UTC, roshangautam requested changes

2018-12-14 05:09 UTC, roshangautam commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
As far as I know `Cache:rememberForEver` returns the value as well. So you can possibly rewrite the `if` statement and the following `return` statement as follows:

```
return Cache::rememberForever('totem.table.'.TOTEM_TABLE_PREFIX.'tasks', function() { 
    Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks'));
});
```

2018-12-14 05:09 UTC, roshangautam commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
Also, the tests are still failing.

2018-12-14 05:12 UTC, qschmick commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
@roshangautam Yes, we could add `rememberForever` but we could only want to do that on a success. If we remember forever the failure we are just wasting the cycles to put that false into cache. I think it's cleaner without it unless we might use it somewhere else and would always want to ensure something is in cache instead of a false-y value of null. Also, working on the tests now

2018-12-14 05:27 UTC, roshangautam commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
Good call. How about we only use `remember`? The cache would be busted according to whatever the timeout has been set by developers. Flipping table prefix wouldn't be a trivial task anyways. WDYT?

2018-12-18 01:58 UTC, roshangautam commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
@qschmick did you get a chance to look a this?

2018-12-19 17:37 UTC, qschmick commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
@roshangautam Are you thinking we'd add a config so someone could set the remember period? Also, as you said with the forever it would get busted if the table prefix was changed. What benefit are you thinking we'd get from using `remember` vs `forever`?

2018-12-20 15:07 UTC, roshangautam commented on src/Totem.php
> +        if (Schema::hasTable(TOTEM_TABLE_PREFIX.'tasks')) {
Thanks for working on this. We can revisit this later. I will merge it for now.

2018-12-20 15:08 UTC, roshangautam approved these changes

2018-12-20 15:09 UTC, merged