Fixes #147 - Sort commands by command name instead of description
codestudiollc/laravel-totem pull request #148
Opened 2019-03-31 20:17 UTC by matthewnessworthy

2019-04-06 16:32 UTC, roshangautam requested changes

2019-04-06 16:32 UTC, roshangautam commented on src/Totem.php
>          });
How about we also update the select options in form.blade.php to go with this. Something like 

```
<optgroup label="{{$command->getDescription()}}">
    <option value="{{$command->getName()}}" {{old('command', $task->command) == $command->getName() ? 'selected' : ''}}>
        {{$command->getName()}}
    </option>
</optgroup>
```

2019-04-07 09:10 UTC, matthewnessworthy commented on src/Totem.php
>          });
Sure, PR updated to reflect these changes

2019-04-07 15:34 UTC, roshangautam commented on src/Totem.php
>          });
Thanks

2019-04-07 15:34 UTC, roshangautam approved these changes

2019-04-07 15:36 UTC, merged