[Feature] Refresh on Execute
codestudiollc/laravel-totem pull request #150
Opened 2019-04-05 14:31 UTC by lroggen

When a task is executed, after is completed the UI is updated with the latest stats

2019-04-06 18:08 UTC, roshangautam requested changes

2019-04-06 18:08 UTC, roshangautam commented on resources/assets/js/tasks/components/TaskRow.vue
> +                return (this.task.average_runtime / 1000).toFixed(2);
this will not work unless you add `average_runtime` to `appends` array of `Task` model.

2019-04-06 18:08 UTC, roshangautam commented on resources/assets/js/tasks/components/TaskRow.vue
> +                return moment(this.task.last_result.ran_at).format('YYYY-MM-DD hh:mm:ss');
you will have to add `last_result` to `appends` array of `Task` model to make this work

2019-04-06 18:08 UTC, roshangautam commented on resources/assets/js/tasks/components/TaskRow.vue
> +    <tr :class="task.is_active ? task.is_active : 'uk-text-danger'">
`<tr :class="task.is_active ? '' : 'uk-text-danger'">`

2019-04-06 18:08 UTC, roshangautam commented on resources/assets/js/tasks/components/TaskRow.vue
> +            seconds() {
nit: `averageDurationInSeconds`

2019-04-06 18:08 UTC, roshangautam commented on resources/assets/js/tasks/components/TaskRow.vue
> +                return (this.task.average_runtime / 1000).toFixed(2);
also this will return a `NaN` if `average_runtime` is 0

2019-04-08 13:39 UTC, lroggen commented on resources/assets/js/tasks/components/TaskRow.vue
> +                return moment(this.task.last_result.ran_at).format('YYYY-MM-DD hh:mm:ss');
Added

2019-04-10 04:34 UTC, roshangautam approved these changes
Looks pretty good. This will be ready to merge once you fix the failing styleci test. Make sure you squash all the commits as well.

2019-04-11 00:00 UTC, roshangautam approved these changes

2019-04-11 00:01 UTC, merged