The date problem in ran_at field was fixed and the parameter field ty…
codestudiollc/laravel-totem pull request #176
Opened 2019-08-27 06:30 UTC by mohsen-farahani

…pe was changed to text and the readme was completed

2019-08-29 04:01 UTC, roshangautam commented
can you please fix the failing tests and also style ci issues ?

2019-08-29 05:52 UTC, roshangautam requested changes
Is there an open issue for this pull request? If not can you please add the problem statement in your commit description? I am trying to understand what's broken and how is it being fixed?

2019-08-29 05:52 UTC, roshangautam commented on README.md
> +php artisan queue:work --queue=queue_default
Can you please help me understand how will this rebuild the cache?

2019-08-29 05:52 UTC, roshangautam commented on database/migrations/2019_08_26_154840_alter_task_results_table_change_type_ran_at_fileds.php
> +class AlterTaskResultsTableChangeTypeRanAtFileds extends Migration
nit: typo in `Fields`

2019-10-25 03:34 UTC, roshangautam commented
any updates here @mohsen-farahani ?

2019-10-28 12:06 UTC, mohsen-farahani commented on README.md
> +php artisan queue:work --queue=queue_default
The cache needs to be cleared when any changes are made.
And this works when the queues are running.
I would have liked to discuss this better here.

2019-11-09 01:40 UTC, roshangautam commented
Can you please update the description with the problem statement? I would really appreciate if you can help me understand the problem you are trying to solve with this PR. Thanks.

2019-11-09 12:31 UTC, mohsen-farahani commented
> Can you please update the description with the problem statement? I would really appreciate if you can help me understand the problem you are trying to solve with this PR. Thanks.

hen we change any tasks configs (for example disable one task) we should update cache manually with
`php artisan cache:clear`
or run queue worker that do it for us
Totem dispatch a job for each change to
`default_queue‍‍‍`
Any where in Readme don't say this and may make misunderstanding

2020-06-07 18:41 UTC, closed without merging