[Fix] Database / Task Visibility Issues
codestudiollc/laravel-totem pull request #198
Opened 2019-11-09 00:37 UTC by b-roberts

2019-11-09 01:36 UTC, roshangautam requested changes
I can't seem to recall why we added that check though? @PS-Qschmick do you recall?

2019-11-09 01:36 UTC, roshangautam commented on src/Providers/ConsoleServiceProvider.php
>          $this->app->resolving(Schedule::class, function ($schedule) {
nit: add a newline after if statement

2019-11-09 01:36 UTC, roshangautam commented on src/Providers/ConsoleServiceProvider.php
> +        if ($this->app->env == 'testing') {
neat. Good call

2019-11-09 01:37 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> -        try {
I meant this one @PS-Qschmick , sorry for the spam :)

2019-11-09 01:43 UTC, b-roberts commented on src/Providers/ConsoleServiceProvider.php
>          $this->app->resolving(Schedule::class, function ($schedule) {
Added.

2019-11-09 01:54 UTC, roshangautam commented on src/Providers/TotemServiceProvider.php
> -        try {
I think I remember now. I know caching is still a problem, but if we remove the check to make sure weather the table exists or not then I think it will throw an error the first time you are install totem in your Laravel project. Immediately after `composer require studio/totem` you will see an error on your terminal. Can you please verify this?

2019-11-09 13:35 UTC, b-roberts commented on src/Providers/TotemServiceProvider.php
> -        try {
Yes, after `composer require` a `QueryException` is thrown because of the missing table. It is the same error I received during unit testing. I am surprised `Schedule` is resolving at this point. 

I think the proper fix would be to have users manually add the `ConsoleServiceProvider` to `config/app.php` after setting up the database. However, without breaking existing installs I suppose checking the database is necessary. I will revisit the issue.

2020-05-15 09:23 UTC, michalper commented
Hi guys, 
any progress here?

2020-05-15 20:19 UTC, Iscrimou commented
> Hi guys,
> any progress here?

I don't think so

2020-05-15 20:19 UTC, Iscrimou commented
This application is deprecated, and doesn't work

2020-05-18 07:44 UTC, michalper commented
Seriously? @Iscrimou is this an official statement?

We got Totem on our production environment already, but in some configurations there are problems with commands visibility in **artisan schedule:list**.

2020-05-18 13:01 UTC, qschmick commented
@Iscrimou @michalper As far as I know this isn't a deprecated application. We still use it in our production systems. A version was just released to support Laravel 7.
@roshangautam will have to speak to support of older versions since right now it's 5.4 through 7.x of Laravel.

Additionally, @b-roberts had a change that was going to be revisited but no update has taken place.

@Iscrimou @michalper please feel free to take from this PR and open your own that address the comments and we can revisit it then. Thank you 😄

2020-06-04 02:33 UTC, roshangautam commented
Thanks @qschmick We try to honor the same support policy as Laravel when it comes to supporting old versions. You can find more details here : https://laravel.com/docs/7.x/releases

But like Quentin said feel free to send a PR to any version you like and we will help review, merge and release it.

2020-08-10 05:39 UTC, closed without merging