Parse quoted parameters
codestudiollc/laravel-totem pull request #81
Opened 2018-03-01 08:33 UTC by pierot

Given parameters: --url='https://noort.be' --header='Authorization: Basic XXX' resulted in the values (for url and header) that were quoted. The PR proposed solves this by trimming the value for single and double quotes.

2018-03-22 02:44 UTC, qschmick requested changes

2018-03-22 02:44 UTC, qschmick commented on src/Task.php
> +                    $value = trim(trim($param[1], '"'), "'");
Can you update this var to `$trimmed_param` or `$cleaned_param` instead of the generic `$value`? Thanks.

2018-03-22 02:44 UTC, qschmick commented
Sorry for the delayed response. Overall look great, one minor update in var name please. Thanks 👍

2018-03-27 07:06 UTC, pierot commented
@qschmick I updated the variables names.

2018-03-27 12:49 UTC, qschmick approved these changes

2018-03-27 12:50 UTC, merged