TotemRouteServiceProvider.php with custom uri
codestudiollc/laravel-totem pull request #91
Opened 2018-03-21 11:38 UTC by frnwtr

enable user to customize the totem uri by settings

2018-03-21 20:26 UTC, qschmick requested changes

2018-03-21 20:26 UTC, qschmick commented on src/Providers/TotemRouteServiceProvider.php
> +            'prefix' => config('totem.uri', 'totem').'/api',
Update this to:
`'prefix' => config('totem.uri', 'totem').'/'.config('totem.api_prefix', 'api'),`

2018-03-22 07:33 UTC, frnwtr commented on src/Providers/TotemRouteServiceProvider.php
> +            'prefix' => config('totem.uri', 'totem').'/api',
seems legit

2018-10-01 17:56 UTC, qschmick approved these changes

2019-01-05 22:52 UTC, roshangautam commented
Closing due to lack of activity

2019-01-05 22:52 UTC, closed without merging